message:
  notdrop: "&cНельзя выкидывать вещи в лобби!"
  notChat: "&cНельзя использовать чат в лобби!"
  notcmd: "нельзя писать команды"
  notperm: "&cНет прав"
  notvoid: "куда ты сьебаться захотел?"
  joinmsg: "[+] Игрок %player% зашел!" # %player% - ник игрока, который зашел
  leavemsgchat: "[-] Игрок %player% вышел!" # %player% - игрок
  reload: "перезагрузил"

  joinmsgchat:
    - "123"
    - "sadf"
    - "sdf"
    - "sdf"

settings:
  cmdUse: true #если true, то команды можно будет юзать
  drop: true #если true, то предметы можно будет выкидывать
  joinmsg: true #если true, то сообщения "игрок такой-то зашел на сервер" или вышел будут показываться
  joinmsgchat: true #если true, то при заходе игроку напишут сообщения в чат
  useChat: true #если true, то игроки смогут писать в чат
  tptovoid: true #если true, то игрока будет тепать на спавн при падении в бездну
  maxHP: 2 #скок у чела макс хп будет

  jointpcord: true #тепать ли игрока при заходе на корды?
  spawn:
    X: 100
    Y: 100
    Z: 100
    pitch: 100
    yaw: 100
    world: "world"
