message:
  notdrop: "&cНельзя выкидывать вещи в лобби!"
  notChat: "&cНельзя использовать чат в лобби!"
  notcmd: "нельзя писать команды"
  notperm: "&cНет прав"
  notvoid: "куда ты сьебаться захотел?"
  joinmsg: "[+] Игрок %player% зашел!" # %player% - ник игрока, который зашел
  leavemsgchat: "[-] Игрок %player% вышел!" # %player% - игрок
  reload: "перезагрузил"

  joinmsgchat:
    - "123"
    - "sadf"
    - "sdf"
    - "sdf"

settings:
  blockCmd: true #если false, то команды можно будет юзать
  blockDrop: true #если true, то предметы можно будет выкидывать
  blockChat: true #если true, то игроки смогут писать в чат
  blockBreak: true #запрещать ли ставить блоки?
  blockPlace: true #запрещать ломать блоки?
  blockPvp: true #запрещать пвп?

  joinmsg: true #если true, то сообщения "игрок такой-то зашел на сервер" или вышел будут показываться
  joinmsgchat: true #если true, то при заходе игроку напишут сообщения в чат

  maxHP: 2 #скок у чела макс хп будет
  GAMEMODE: "CREATIVE" #режим игры при заходе

  killtovoid: true #если true, то игрока будет убивать если он окажется ниже 10 высоты
  jointpcord: true #тепать ли игрока при заходе на корды?
  spawn:
    x: 120.0
    y: 140.0
    z: 150.0
    pitch: 100
    yaw: 100
    world: "world"
item:
  enable: true
  material: "COMPASS"
  name: "выбор сервера"
  lore:
    - "adsf"
    - " fds"
    - " fds"
  open_command: "dm open %player% server" # %player% - игрок
  glow: true